name: build

on:
  push:
    branches:
      - main
      - develop
      - feature/*
      - fix/*
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  schedule:
    - cron: '0 9 * * 3'
  workflow_dispatch:

jobs:
  run-tests:
    name: run-tests
    strategy:
      matrix:
        node:
          - 16
          - 18
    runs-on: ubuntu-latest
    steps:
      - name: checkout-node-${{matrix.node}}
        uses: actions/checkout@v3
      - name: setup-node-${{matrix.node}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node}}
      - name: npm-ci-node-${{matrix.node}}
        run: npm ci
      - name: npm-run-lint-node-${{matrix.node}}
        run: npm run lint
      - name: npm-run-test-node-${{matrix.node}}
        run: npm run coverage
      - name: upload-coverage-node-${{matrix.node}}
        uses: actions/upload-artifact@v1
        with:
          name: azamcodec_js_coverage_node_${{matrix.node}}_${{github.sha}}
          path: ./coverage
